Mon Jan 23 09:01:30 CET 2017 : Server di rete Apache Derby: 10.11.1.2 - (1629631) avviato e pronto ad accettare connessioni sulla porta 1527
----------------------------------------------------------------
Mon Jan 23 09:01:30 CET 2017:
Avvio della versione di Derby The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): istanza a816c00e-0159-ca58-1edb-ffffc0ef4d72
sulla directory di database C:\Users\claar\Documents\NetBeansProjects\amministrazionesistema\Sito Amm\web\WEB-INF\db\prova con caricatore classi sun.misc.Launcher$AppClassLoader@6f94fa3e 
Caricato da file:/D:/Programmi/Java%20KIT/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_112-b15
user.dir=D:\Programmi\Java KIT\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\claar\Documents\NetBeansProjects\amministrazionesistema\Sito Amm\web\WEB-INF\db
Programma di caricamento classe database avviato - derby.database.classpath=''
----------------------------------------------------------------
Mon Jan 23 09:01:32 CET 2017:
Arresto dell'istanza a816c00e-0159-ca58-1edb-ffffc0ef4d72 nella directory del database C:\Users\claar\Documents\NetBeansProjects\amministrazionesistema\Sito Amm\web\WEB-INF\db\prova con il caricatore di classi sun.misc.Launcher$AppClassLoader@6f94fa3e 
Mon Jan 23 09:01:32 CET 2017 Thread[DRDAConnThread_2,5,main] (DATABASE = prova), (DRDAID = {2}), Chiusura del database 'prova'.
----------------------------------------------------------------
Mon Jan 23 09:04:29 CET 2017:
Avvio della versione di Derby The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): istanza a65c80ac-0159-ca58-1edb-ffffc0ef4d72
sulla directory di database C:\Users\claar\Documents\NetBeansProjects\amministrazionesistema\Sito Amm\web\WEB-INF\db\prova con caricatore classi sun.misc.Launcher$AppClassLoader@6f94fa3e 
Caricato da file:/D:/Programmi/Java%20KIT/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_112-b15
user.dir=D:\Programmi\Java KIT\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\claar\Documents\NetBeansProjects\amministrazionesistema\Sito Amm\web\WEB-INF\db
Programma di caricamento classe database avviato - derby.database.classpath=''
----------------------------------------------------------------
Mon Jan 23 09:22:35 CET 2017:
Avvio della versione di Derby The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): istanza 2aed0129-0159-ca58-1edb-ffffc0ef4d72
sulla directory di database C:\Users\claar\Documents\NetBeansProjects\amministrazionesistema\Sito Amm\web\WEB-INF\db\ammdb con caricatore classi sun.misc.Launcher$AppClassLoader@6f94fa3e 
Caricato da file:/D:/Programmi/Java%20KIT/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_112-b15
user.dir=D:\Programmi\Java KIT\db
os.name=Windows 10
os.arch=amd64
os.version=10.0
derby.system.home=C:\Users\claar\Documents\NetBeansProjects\amministrazionesistema\Sito Amm\web\WEB-INF\db
Programma di caricamento classe database avviato - derby.database.classpath=''
Mon Jan 23 12:25:45 CET 2017 Thread[DRDAConnThread_3,5,main] (XID = 315), (SESSIONID = 2), (DATABASE = prova), (DRDAID = {5}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Autenticazione della connessione non riuscita. Motivo: Autenticazione non valida..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR 08004: Autenticazione della connessione non riuscita. Motivo: Autenticazione non valida..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR 08004: Autenticazione della connessione non riuscita. Motivo: Autenticazione non valida..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Mon Jan 23 12:25:45 CET 2017 Thread[DRDAConnThread_3,5,main] (DATABASE = prova), (DRDAID = {5}), Autenticazione della connessione non riuscita. Motivo: Autenticazione non valida..
